import 'package:freezed_annotation/freezed_annotation.dart';

part 'country_code.freezed.dart';
part 'country_code.g.dart';

const List<PhoneCode> countryPhoneCodes = [
  PhoneCode(name: "Afghanistan", dialCode: "+93", emoji: "🇦🇫", code: "AF"),
  PhoneCode(name: "Aland Islands", dialCode: "+358", emoji: "🇦🇽", code: "AX"),
  PhoneCode(name: "Albania", dialCode: "+355", emoji: "🇦🇱", code: "AL"),
  PhoneCode(name: "Algeria", dialCode: "+213", emoji: "🇩🇿", code: "DZ"),
  PhoneCode(
      name: "AmericanSamoa", dialCode: "+1684", emoji: "🇦🇸", code: "AS"),
  PhoneCode(name: "Andorra", dialCode: "+376", emoji: "🇦🇩", code: "AD"),
  PhoneCode(name: "Angola", dialCode: "+244", emoji: "🇦🇴", code: "AO"),
  PhoneCode(name: "Anguilla", dialCode: "+1264", emoji: "🇦🇮", code: "AI"),
  PhoneCode(name: "Antarctica", dialCode: "+672", emoji: "🇦🇶", code: "AQ"),
  PhoneCode(
      name: "Antigua and Barbuda",
      dialCode: "+1268",
      emoji: "🇦🇬",
      code: "AG"),
  PhoneCode(name: "Argentina", dialCode: "+54", emoji: "🇦🇷", code: "AR"),
  PhoneCode(name: "Armenia", dialCode: "+374", emoji: "🇦🇲", code: "AM"),
  PhoneCode(name: "Aruba", dialCode: "+297", emoji: "🇦🇼", code: "AW"),
  PhoneCode(name: "Australia", dialCode: "+61", emoji: "🇦🇺", code: "AU"),
  PhoneCode(name: "Austria", dialCode: "+43", emoji: "🇦🇹", code: "AT"),
  PhoneCode(name: "Azerbaijan", dialCode: "+994", emoji: "🇦🇿", code: "AZ"),
  PhoneCode(name: "Bahamas", dialCode: "+1242", emoji: "🇧🇸", code: "BS"),
  PhoneCode(name: "Bahrain", dialCode: "+973", emoji: "🇧🇭", code: "BH"),
  PhoneCode(name: "Bangladesh", dialCode: "+880", emoji: "🇧🇩", code: "BD"),
  PhoneCode(name: "Barbados", dialCode: "+1246", emoji: "🇧🇧", code: "BB"),
  PhoneCode(name: "Belarus", dialCode: "+375", emoji: "🇧🇾", code: "BY"),
  PhoneCode(name: "Belgium", dialCode: "+32", emoji: "🇧🇪", code: "BE"),
  PhoneCode(name: "Belize", dialCode: "+501", emoji: "🇧🇿", code: "BZ"),
  PhoneCode(name: "Benin", dialCode: "+229", emoji: "🇧🇯", code: "BJ"),
  PhoneCode(name: "Bermuda", dialCode: "+1441", emoji: "🇧🇲", code: "BM"),
  PhoneCode(name: "Bhutan", dialCode: "+975", emoji: "🇧🇹", code: "BT"),
  PhoneCode(
      name: "Bolivia, Plurinational State of",
      dialCode: "+591",
      emoji: "🇧🇴",
      code: "BO"),
  PhoneCode(
      name: "Bosnia and Herzegovina",
      dialCode: "+387",
      emoji: "🇧🇦",
      code: "BA"),
  PhoneCode(name: "Botswana", dialCode: "+267", emoji: "🇧🇼", code: "BW"),
  PhoneCode(name: "Brazil", dialCode: "+55", emoji: "🇧🇷", code: "BR"),
  PhoneCode(
      name: "British Indian Ocean Territory",
      dialCode: "+246",
      emoji: "🇮🇴",
      code: "IO"),
  PhoneCode(
      name: "Brunei Darussalam", dialCode: "+673", emoji: "🇧🇳", code: "BN"),
  PhoneCode(name: "Bulgaria", dialCode: "+359", emoji: "🇧🇬", code: "BG"),
  PhoneCode(name: "Burkina Faso", dialCode: "+226", emoji: "🇧🇫", code: "BF"),
  PhoneCode(name: "Burundi", dialCode: "+257", emoji: "🇧🇮", code: "BI"),
  PhoneCode(name: "Cambodia", dialCode: "+855", emoji: "🇰🇭", code: "KH"),
  PhoneCode(name: "Cameroon", dialCode: "+237", emoji: "🇨🇲", code: "CM"),
  PhoneCode(name: "Canada", dialCode: "+1", emoji: "🇨🇦", code: "CA"),
  PhoneCode(name: "Cape Verde", dialCode: "+238", emoji: "🇨🇻", code: "CV"),
  PhoneCode(
      name: "Cayman Islands", dialCode: "+345", emoji: "🇰🇾", code: "KY"),
  PhoneCode(
      name: "Central African Republic",
      dialCode: "+236",
      emoji: "🇨🇫",
      code: "CF"),
  PhoneCode(name: "Chad", dialCode: "+235", emoji: "🇹🇩", code: "TD"),
  PhoneCode(name: "Chile", dialCode: "+56", emoji: "🇨🇱", code: "CL"),
  PhoneCode(name: "China", dialCode: "+86", emoji: "🇨🇳", code: "CN"),
  PhoneCode(
      name: "Christmas Island", dialCode: "+61", emoji: "🇨🇽", code: "CX"),
  PhoneCode(
      name: "Cocos (Keeling) Islands",
      dialCode: "+61",
      emoji: "🇨🇨",
      code: "CC"),
  PhoneCode(name: "Colombia", dialCode: "+57", emoji: "🇨🇴", code: "CO"),
  PhoneCode(name: "Comoros", dialCode: "+269", emoji: "🇰🇲", code: "KM"),
  PhoneCode(name: "Congo", dialCode: "+242", emoji: "🇨🇬", code: "CG"),
  PhoneCode(
      name: "Congo, The Democratic Republic of the Congo",
      dialCode: "+243",
      emoji: "🇨🇩",
      code: "CD"),
  PhoneCode(name: "Cook Islands", dialCode: "+682", emoji: "🇨🇰", code: "CK"),
  PhoneCode(name: "Costa Rica", dialCode: "+506", emoji: "🇨🇷", code: "CR"),
  PhoneCode(name: "Cote d'Ivoire", dialCode: "+225", emoji: "🇨🇮", code: "CI"),
  PhoneCode(name: "Croatia", dialCode: "+385", emoji: "🇭🇷", code: "HR"),
  PhoneCode(name: "Cuba", dialCode: "+53", emoji: "🇨🇺", code: "CU"),
  PhoneCode(name: "Cyprus", dialCode: "+357", emoji: "🇨🇾", code: "CY"),
  PhoneCode(
      name: "Czech Republic", dialCode: "+420", emoji: "🇨🇿", code: "CZ"),
  PhoneCode(name: "Denmark", dialCode: "+45", emoji: "🇩🇰", code: "DK"),
  PhoneCode(name: "Djibouti", dialCode: "+253", emoji: "🇩🇯", code: "DJ"),
  PhoneCode(name: "Dominica", dialCode: "+1767", emoji: "🇩🇲", code: "DM"),
  PhoneCode(
      name: "Dominican Republic", dialCode: "+1849", emoji: "🇩🇴", code: "DO"),
  PhoneCode(name: "Ecuador", dialCode: "+593", emoji: "🇪🇨", code: "EC"),
  PhoneCode(name: "Egypt", dialCode: "+20", emoji: "🇪🇬", code: "EG"),
  PhoneCode(name: "El Salvador", dialCode: "+503", emoji: "🇸🇻", code: "SV"),
  PhoneCode(
      name: "Equatorial Guinea", dialCode: "+240", emoji: "🇬🇶", code: "GQ"),
  PhoneCode(name: "Eritrea", dialCode: "+291", emoji: "🇪🇷", code: "ER"),
  PhoneCode(name: "Estonia", dialCode: "+372", emoji: "🇪🇪", code: "EE"),
  PhoneCode(name: "Ethiopia", dialCode: "+251", emoji: "🇪🇹", code: "ET"),
  PhoneCode(
      name: "Falkland Islands (Malvinas)",
      dialCode: "+500",
      emoji: "🇫🇰",
      code: "FK"),
  PhoneCode(name: "Faroe Islands", dialCode: "+298", emoji: "🇫🇴", code: "FO"),
  PhoneCode(name: "Fiji", dialCode: "+679", emoji: "🇫🇯", code: "FJ"),
  PhoneCode(name: "Finland", dialCode: "+358", emoji: "🇫🇮", code: "FI"),
  PhoneCode(name: "France", dialCode: "+33", emoji: "🇫🇷", code: "FR"),
  PhoneCode(name: "French Guiana", dialCode: "+594", emoji: "🇬🇫", code: "GF"),
  PhoneCode(
      name: "French Polynesia", dialCode: "+689", emoji: "🇵🇫", code: "PF"),
  PhoneCode(name: "Gabon", dialCode: "+241", emoji: "🇬🇦", code: "GA"),
  PhoneCode(name: "Gambia", dialCode: "+220", emoji: "🇬🇲", code: "GM"),
  PhoneCode(name: "Georgia", dialCode: "+995", emoji: "🇬🇪", code: "GE"),
  PhoneCode(name: "Germany", dialCode: "+49", emoji: "🇩🇪", code: "DE"),
  PhoneCode(name: "Ghana", dialCode: "+233", emoji: "🇬🇭", code: "GH"),
  PhoneCode(name: "Gibraltar", dialCode: "+350", emoji: "🇬🇮", code: "GI"),
  PhoneCode(name: "Greece", dialCode: "+30", emoji: "🇬🇷", code: "GR"),
  PhoneCode(name: "Greenland", dialCode: "+299", emoji: "🇬🇱", code: "GL"),
  PhoneCode(name: "Grenada", dialCode: "+1473", emoji: "🇬🇩", code: "GD"),
  PhoneCode(name: "Guadeloupe", dialCode: "+590", emoji: "🇬🇵", code: "GP"),
  PhoneCode(name: "Guam", dialCode: "+1671", emoji: "🇬🇺", code: "GU"),
  PhoneCode(name: "Guatemala", dialCode: "+502", emoji: "🇬🇹", code: "GT"),
  PhoneCode(name: "Guernsey", dialCode: "+44", emoji: "🇬🇬", code: "GG"),
  PhoneCode(name: "Guinea", dialCode: "+224", emoji: "🇬🇳", code: "GN"),
  PhoneCode(name: "Guinea-Bissau", dialCode: "+245", emoji: "🇬🇼", code: "GW"),
  PhoneCode(name: "Guyana", dialCode: "+595", emoji: "🇬🇾", code: "GY"),
  PhoneCode(name: "Haiti", dialCode: "+509", emoji: "🇭🇹", code: "HT"),
  PhoneCode(
      name: "Holy See (Vatican City State)",
      dialCode: "+379",
      emoji: "🇻🇦",
      code: "VA"),
  PhoneCode(name: "Honduras", dialCode: "+504", emoji: "🇭🇳", code: "HN"),
  PhoneCode(name: "Hong Kong", dialCode: "+852", emoji: "🇭🇰", code: "HK"),
  PhoneCode(name: "Hungary", dialCode: "+36", emoji: "🇭🇺", code: "HU"),
  PhoneCode(name: "Iceland", dialCode: "+354", emoji: "🇮🇸", code: "IS"),
  PhoneCode(name: "India", dialCode: "+91", emoji: "🇮🇳", code: "IN"),
  PhoneCode(name: "Indonesia", dialCode: "+62", emoji: "🇮🇩", code: "ID"),
  PhoneCode(
      name: "Iran, Islamic Republic of Persian Gulf",
      dialCode: "+98",
      emoji: "🇮🇷",
      code: "IR"),
  PhoneCode(name: "Iraq", dialCode: "+964", emoji: "🇮🇷", code: "IQ"),
  PhoneCode(name: "Ireland", dialCode: "+353", emoji: "🇮🇪", code: "IE"),
  PhoneCode(name: "Isle of Man", dialCode: "+44", emoji: "🇮🇲", code: "IM"),
  PhoneCode(name: "Israel", dialCode: "+972", emoji: "🇮🇱", code: "IL"),
  PhoneCode(name: "Italy", dialCode: "+39", emoji: "🇮🇹", code: "IT"),
  PhoneCode(name: "Jamaica", dialCode: "+1876", emoji: "🇯🇲", code: "JM"),
  PhoneCode(name: "Japan", dialCode: "+81", emoji: "🇯🇵", code: "JP"),
  PhoneCode(name: "Jersey", dialCode: "+44", emoji: "🇯🇪", code: "JE"),
  PhoneCode(name: "Jordan", dialCode: "+962", emoji: "🇯🇴", code: "JO"),
  PhoneCode(name: "Kazakhstan", dialCode: "+77", emoji: "🇰🇿", code: "KZ"),
  PhoneCode(name: "Kenya", dialCode: "+254", emoji: "🇰🇪", code: "KE"),
  PhoneCode(name: "Kiribati", dialCode: "+686", emoji: "🇰🇮", code: "KI"),
  PhoneCode(
      name: "Korea, Democratic People's Republic of Korea",
      dialCode: "+850",
      emoji: "🇰🇵",
      code: "KP"),
  PhoneCode(
      name: "Korea, Republic of South Korea",
      dialCode: "+82",
      emoji: "🇰🇷",
      code: "KR"),
  PhoneCode(name: "Kuwait", dialCode: "+965", emoji: "🇰🇼", code: "KW"),
  PhoneCode(name: "Kyrgyzstan", dialCode: "+996", emoji: "🇰🇬", code: "KG"),
  PhoneCode(name: "Laos", dialCode: "+856", emoji: "🇱🇦", code: "LA"),
  PhoneCode(name: "Latvia", dialCode: "+371", emoji: "🇱🇻", code: "LV"),
  PhoneCode(name: "Lebanon", dialCode: "+961", emoji: "🇱🇧", code: "LB"),
  PhoneCode(name: "Lesotho", dialCode: "+266", emoji: "🇱🇸", code: "LS"),
  PhoneCode(name: "Liberia", dialCode: "+231", emoji: "🇱🇷", code: "LR"),
  PhoneCode(
      name: "Libyan Arab Jamahiriya",
      dialCode: "+218",
      emoji: "🇱🇾",
      code: "LY"),
  PhoneCode(name: "Liechtenstein", dialCode: "+423", emoji: "🇱🇮", code: "LI"),
  PhoneCode(name: "Lithuania", dialCode: "+370", emoji: "🇱🇹", code: "LT"),
  PhoneCode(name: "Luxembourg", dialCode: "+352", emoji: "🇱🇺", code: "LU"),
  PhoneCode(name: "Macao", dialCode: "+853", emoji: "🇲🇴", code: "MO"),
  PhoneCode(name: "Macedonia", dialCode: "+389", emoji: "🇲🇰", code: "MK"),
  PhoneCode(name: "Madagascar", dialCode: "+261", emoji: "🇲🇬", code: "MG"),
  PhoneCode(name: "Malawi", dialCode: "+265", emoji: "🇲🇼", code: "MW"),
  PhoneCode(name: "Malaysia", dialCode: "+60", emoji: "🇲🇾", code: "MY"),
  PhoneCode(name: "Maldives", dialCode: "+960", emoji: "🇲🇻", code: "MV"),
  PhoneCode(name: "Mali", dialCode: "+223", emoji: "🇲🇱", code: "ML"),
  PhoneCode(name: "Malta", dialCode: "+356", emoji: "🇲🇹", code: "MT"),
  PhoneCode(
      name: "Marshall Islands", dialCode: "+692", emoji: "🇲🇭", code: "MH"),
  PhoneCode(name: "Martinique", dialCode: "+596", emoji: "🇲🇶", code: "MQ"),
  PhoneCode(name: "Mauritania", dialCode: "+222", emoji: "🇲🇷", code: "MR"),
  PhoneCode(name: "Mauritius", dialCode: "+230", emoji: "🇲🇺", code: "MU"),
  PhoneCode(name: "Mayotte", dialCode: "+262", emoji: "🇾🇹", code: "YT"),
  PhoneCode(name: "Mexico", dialCode: "+52", emoji: "🇲🇽", code: "MX"),
  PhoneCode(
      name: "Micronesia, Federated States of Micronesia",
      dialCode: "+691",
      emoji: "🇫🇲",
      code: "FM"),
  PhoneCode(name: "Moldova", dialCode: "+373", emoji: "🇲🇩", code: "MD"),
  PhoneCode(name: "Monaco", dialCode: "+377", emoji: "🇲🇨", code: "MC"),
  PhoneCode(name: "Mongolia", dialCode: "+976", emoji: "🇲🇳", code: "MN"),
  PhoneCode(name: "Montenegro", dialCode: "+382", emoji: "🇲🇪", code: "ME"),
  PhoneCode(name: "Montserrat", dialCode: "+1664", emoji: "🇲🇸", code: "MS"),
  PhoneCode(name: "Morocco", dialCode: "+212", emoji: "🇲🇦", code: "MA"),
  PhoneCode(name: "Mozambique", dialCode: "+258", emoji: "🇲🇿", code: "MZ"),
  PhoneCode(name: "Myanmar", dialCode: "+95", emoji: "🇲🇲", code: "MM"),
  PhoneCode(name: "Namibia", emoji: "🇳🇦", dialCode: "+264", code: "NA"),
  PhoneCode(name: "Nauru", dialCode: "+674", emoji: "🇳🇷", code: "NR"),
  PhoneCode(name: "Nepal", dialCode: "+977", emoji: "🇳🇵", code: "NP"),
  PhoneCode(name: "Netherlands", dialCode: "+31", emoji: "🇳🇱", code: "NL"),
  PhoneCode(
      name: "Netherlands Antilles",
      dialCode: "+599",
      emoji: "🇧🇶",
      code: "AN"),
  PhoneCode(name: "New Caledonia", dialCode: "+687", emoji: "🇳🇨", code: "NC"),
  PhoneCode(name: "New Zealand", dialCode: "+64", emoji: "🇳🇿", code: "NZ"),
  PhoneCode(name: "Nicaragua", dialCode: "+505", emoji: "🇳🇮", code: "NI"),
  PhoneCode(name: "Niger", dialCode: "+227", emoji: "🇳🇪", code: "NE"),
  PhoneCode(name: "Nigeria", dialCode: "+234", emoji: "🇳🇬", code: "NG"),
  PhoneCode(name: "Niue", dialCode: "+683", emoji: "🇳🇺", code: "NU"),
  PhoneCode(
      name: "Norfolk Island", dialCode: "+672", emoji: "🇳🇫", code: "NF"),
  PhoneCode(
      name: "Northern Mariana Islands",
      dialCode: "+1670",
      emoji: "🇲🇵",
      code: "MP"),
  PhoneCode(name: "Norway", dialCode: "+47", emoji: "🇳🇴", code: "NO"),
  PhoneCode(name: "Oman", dialCode: "+968", emoji: "🇴🇲", code: "OM"),
  PhoneCode(name: "Pakistan", dialCode: "+92", emoji: "🇵🇰", code: "PK"),
  PhoneCode(name: "Palau", dialCode: "+680", emoji: "🇵🇼", code: "PW"),
  PhoneCode(
      name: "Palestinian Territory, Occupied",
      dialCode: "+970",
      emoji: "🇵🇸",
      code: "PS"),
  PhoneCode(name: "Panama", dialCode: "+507", emoji: "🇵🇦", code: "PA"),
  PhoneCode(
      name: "Papua New Guinea", dialCode: "+675", emoji: "🇵🇬", code: "PG"),
  PhoneCode(name: "Paraguay", dialCode: "+595", emoji: "🇵🇾", code: "PY"),
  PhoneCode(name: "Peru", dialCode: "+51", emoji: "🇵🇪", code: "PE"),
  PhoneCode(name: "Philippines", dialCode: "+63", emoji: "🇵🇭", code: "PH"),
  PhoneCode(name: "Pitcairn", dialCode: "+872", emoji: "🇵🇳", code: "PN"),
  PhoneCode(name: "Poland", dialCode: "+48", emoji: "🇵🇱", code: "PL"),
  PhoneCode(name: "Portugal", dialCode: "+351", emoji: "🇵🇹", code: "PT"),
  PhoneCode(name: "Puerto Rico", dialCode: "+1939", emoji: "🇵🇷", code: "PR"),
  PhoneCode(name: "Qatar", dialCode: "+974", emoji: "🇶🇦", code: "QA"),
  PhoneCode(name: "Romania", dialCode: "+40", emoji: "🇷🇴", code: "RO"),
  PhoneCode(name: "Russia", dialCode: "+7", emoji: "🇷🇺", code: "RU"),
  PhoneCode(name: "Rwanda", dialCode: "+250", emoji: "🇷🇼", code: "RW"),
  PhoneCode(name: "Reunion", dialCode: "+262", emoji: "🇷🇪", code: "RE"),
  PhoneCode(
      name: "Saint Barthelemy", dialCode: "+590", emoji: "🇧🇱", code: "BL"),
  PhoneCode(
      name: "Saint Helena, Ascension and Tristan Da Cunha",
      dialCode: "+290",
      emoji: "🇸🇭",
      code: "SH"),
  PhoneCode(
      name: "Saint Kitts and Nevis",
      dialCode: "+1869",
      emoji: "🇰🇳",
      code: "KN"),
  PhoneCode(name: "Saint Lucia", dialCode: "+1758", emoji: "🇱🇨", code: "LC"),
  PhoneCode(name: "Saint Martin", dialCode: "+590", emoji: "🇲🇫", code: "MF"),
  PhoneCode(
      name: "Saint Pierre and Miquelon",
      dialCode: "+508",
      emoji: "🇵🇲",
      code: "PM"),
  PhoneCode(
      name: "Saint Vincent and the Grenadines",
      dialCode: "+1784",
      emoji: "🇻🇨",
      code: "VC"),
  PhoneCode(name: "Samoa", dialCode: "+685", emoji: "🇼🇸", code: "WS"),
  PhoneCode(name: "San Marino", dialCode: "+378", emoji: "🇸🇲", code: "SM"),
  PhoneCode(
      name: "Sao Tome and Principe",
      dialCode: "+239",
      emoji: "🇸🇹",
      code: "ST"),
  PhoneCode(name: "Saudi Arabia", dialCode: "+966", emoji: "🇸🇦", code: "SA"),
  PhoneCode(name: "Senegal", dialCode: "+221", emoji: "🇸🇳", code: "SN"),
  PhoneCode(name: "Serbia", dialCode: "+381", emoji: "🇷🇸", code: "RS"),
  PhoneCode(name: "Seychelles", dialCode: "+248", emoji: "🇸🇨", code: "SC"),
  PhoneCode(name: "Sierra Leone", dialCode: "+232", emoji: "🇸🇱", code: "SL"),
  PhoneCode(name: "Singapore", dialCode: "+65", emoji: "🇸🇬", code: "SG"),
  PhoneCode(name: "Slovakia", dialCode: "+421", emoji: "🇸🇰", code: "SK"),
  PhoneCode(name: "Slovenia", dialCode: "+386", emoji: "🇸🇮", code: "SI"),
  PhoneCode(
      name: "Solomon Islands", dialCode: "+677", emoji: "🇸🇧", code: "SB"),
  PhoneCode(name: "Somalia", dialCode: "+252", emoji: "🇸🇴", code: "SO"),
  PhoneCode(name: "South Africa", dialCode: "+27", emoji: "🇿🇦", code: "ZA"),
  PhoneCode(name: "South Sudan", dialCode: "+211", emoji: "🇸🇸", code: "SS"),
  PhoneCode(
      name: "South Georgia and the South Sandwich Islands",
      dialCode: "+500",
      emoji: "🇬🇸",
      code: "GS"),
  PhoneCode(name: "Spain", dialCode: "+34", emoji: "🇪🇸", code: "ES"),
  PhoneCode(name: "Sri Lanka", dialCode: "+94", emoji: "🇱🇰", code: "LK"),
  PhoneCode(name: "Sudan", dialCode: "+249", emoji: "🇸🇩", code: "SD"),
  PhoneCode(name: "Suriname", dialCode: "+597", emoji: "🇸🇷", code: "SR"),
  PhoneCode(
      name: "Svalbard and Jan Mayen",
      dialCode: "+47",
      emoji: "🇸🇯",
      code: "SJ"),
  PhoneCode(name: "Swaziland", dialCode: "+268", emoji: "🇸🇿", code: "SZ"),
  PhoneCode(name: "Sweden", dialCode: "+46", emoji: "🇸🇪", code: "SE"),
  PhoneCode(name: "Switzerland", dialCode: "+41", emoji: "🇨🇭", code: "CH"),
  PhoneCode(
      name: "Syrian Arab Republic",
      dialCode: "+963",
      emoji: "🇸🇾",
      code: "SY"),
  PhoneCode(name: "Taiwan", dialCode: "+886", emoji: "🇹🇼", code: "TW"),
  PhoneCode(name: "Tajikistan", dialCode: "+992", emoji: "🇹🇯", code: "TJ"),
  PhoneCode(
      name: "Tanzania, United Republic of Tanzania",
      dialCode: "+255",
      emoji: "🇹🇿",
      code: "TZ"),
  PhoneCode(name: "Thailand", dialCode: "+66", emoji: "🇹🇭", code: "TH"),
  PhoneCode(name: "Timor-Leste", dialCode: "+670", emoji: "🇹🇱", code: "TL"),
  PhoneCode(name: "Togo", dialCode: "+228", emoji: "🇹🇬", code: "TG"),
  PhoneCode(name: "Tokelau", dialCode: "+690", emoji: "🇹🇰", code: "TK"),
  PhoneCode(name: "Tonga", dialCode: "+676", emoji: "🇹🇴", code: "TO"),
  PhoneCode(
      name: "Trinidad and Tobago",
      dialCode: "+1868",
      emoji: "🇹🇹",
      code: "TT"),
  PhoneCode(name: "Tunisia", dialCode: "+216", emoji: "🇹🇳", code: "TN"),
  PhoneCode(name: "Turkey", dialCode: "+90", emoji: "🇹🇷", code: "TR"),
  PhoneCode(name: "Turkmenistan", dialCode: "+993", emoji: "🇹🇲", code: "TM"),
  PhoneCode(
      name: "Turks and Caicos Islands",
      dialCode: "+1649",
      emoji: "🇹🇨",
      code: "TC"),
  PhoneCode(name: "Tuvalu", dialCode: "+688", emoji: "🇹🇻", code: "TV"),
  PhoneCode(name: "Uganda", dialCode: "+256", emoji: "🇺🇬", code: "UG"),
  PhoneCode(name: "Ukraine", dialCode: "+380", emoji: "🇺🇦", code: "UA"),
  PhoneCode(
      name: "United Arab Emirates",
      dialCode: "+971",
      emoji: "🇦🇪",
      code: "AE"),
  PhoneCode(name: "United Kingdom", dialCode: "+44", emoji: "🇬🇧", code: "GB"),
  PhoneCode(name: "United States", dialCode: "+1", emoji: "🇺🇸", code: "US"),
  PhoneCode(name: "Uruguay", dialCode: "+598", emoji: "🇺🇾", code: "UY"),
  PhoneCode(name: "Uzbekistan", dialCode: "+998", emoji: "🇺🇿", code: "UZ"),
  PhoneCode(name: "Vanuatu", dialCode: "+678", emoji: "🇻🇺", code: "VU"),
  PhoneCode(
      name: "Venezuela, Bolivarian Republic of Venezuela",
      dialCode: "+58",
      emoji: "🇻🇪",
      code: "VE"),
  PhoneCode(name: "Vietnam", dialCode: "+84", emoji: "🇻🇳", code: "VN"),
  PhoneCode(
      name: "Virgin Islands, British",
      dialCode: "+1284",
      emoji: "🇻🇬",
      code: "VG"),
  PhoneCode(
      name: "Virgin Islands, U.S.",
      dialCode: "+1340",
      emoji: "🇻🇮",
      code: "VI"),
  PhoneCode(
      name: "Wallis and Futuna", dialCode: "+681", emoji: "🇼🇫", code: "WF"),
  PhoneCode(name: "Yemen", dialCode: "+967", emoji: "🇾🇪", code: "YE"),
  PhoneCode(name: "Zambia", dialCode: "+260", emoji: "🇿🇲", code: "ZM"),
  PhoneCode(name: "Zimbabwe", dialCode: "+263", emoji: "🇿🇼", code: "ZW")
];

@freezed
class PhoneCode with _$PhoneCode {
  const factory PhoneCode({
    required String name,
    required String dialCode,
    String? emoji,
    required String code,
  }) = _PhoneCode;

  factory PhoneCode.fromJson(Map<String, dynamic> json) =>
      _$PhoneCodeFromJson(json);
}
